### ISSUE TITLE
Refactor code from controllers into separate methods

### ISSUE THREAD

**Issue by nickserv** [toroidal-code/codeflash#118]
This way, Code Climate can like our code more.

**Comment by kristenmills** [comment]
i think this is done. @thenickperson  verify?

**Comment by nickserv** [comment]
https://codeclimate.com/github/codeflash/codeflash/constants?sort=remediation_cost&sort_direction=desc

At this point, we still have 3 Ds and 1 C, and they're all controllers. I think we should continue working on this until we get a 4.0 on Code Climate. Yeah it's more work, but our code will be much more maintainable in the end.

**Comment by smy2748** [comment]
Well we should be doing this more for the reason that we want our code to be more maintainable, coherent, cohesive, and extendable than making code climate like it.

What I'm saying is, change stuff if you as developer believe that it would benefit us in the long run, but don't change it just because a static analysis tool says to.

**Comment by nickserv** [comment]
Agreed, I just trust Code Climate and use it as a reminder to make things more maintainable/DRY/simple/etc.

**Comment by smy2748** [comment]
Due to the way the framework works, we can't appease it all over the board.

**Comment by kristenmills** [comment]
I'm closing this.
