### ISSUE TITLE
Prepare for Rails 4

### ISSUE THREAD

**Issue by toroidal-code** [toroidal-code/codeflash#132]
Rails 4 is going to be released in few months, so it would be a good idea to slowly migrate to make the upgrade as painless as possible.

There's a couple articles about the best methods for upgrade, this'll be a good place to put them.

http://rubysource.com/get-your-app-ready-for-rails-4/

Steps to be taken. (This is not a comprehensive or complete list)
- [x] Replace model-based mass assignment (attr_accessible) with new protection model for params(strong_parameters) 
- [x] Use strong_parameters in dev branch instead of attr_accessible

**Comment by nickserv** [comment]
This is also a pretty useful guide: http://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-3-2-to-rails-4-0

Also, there are some warnings we're getting about things that changed in Rails 4 and the newer version of Sass. I can help you fix this, since I just fixed a bunch of Rails 4 warnings for another app.

**Comment by nickserv** [comment]
Please note that we are now primarily developing for Rails 4.0. However, the tasks in this issue are still not complete.

**Comment by nickserv** [comment]
Rails 4.0 support is now merged into dev. Please contribute to it on the dev branch (unless if it makes sense to make a feature branch for whatever you're doing).

**Comment by toroidal-code** [comment]
closed by 
cd740bc4b8
