### ISSUE TITLE
Ruby 2.0

### ISSUE THREAD

**Issue by toroidal-code** [toroidal-code/codeflash#148]
Ruby 2.0 is released, and Nick suggested having Codeflash be future-proofed somehow and compatible with it. I'm not against this, but as it stands, production machines are running rbx-2.0rc1 in 1.9 mode. Thoughts?

**Comment by nickserv** [comment]
I think we should aim to support both Ruby 1.9.3 and Ruby 2.0, even though we might only us Rubinius in 1.9 mode for now. People's development environments are going to update Ruby versions, and Ruby 2.0 should be almost complete compatible with 1.9.3 code. Also, we can always have Travis build on both versions of Ruby. Finally, Rails should support Ruby 2.0 just fine (in fact, it should have much faster load times).

**Comment by kristenmills** [comment]
ruby 2.0 has 5 incompatibilities known none of which should affect us. 
- The default encoding for ruby scripts is now UTF-8 [#6679]. Some people report that it affects existing programs, such as some benchmark programs becoming very slow [ruby-dev:46547].
- Iconv was removed, which had already been deprecated when M17N was introduced in ruby 1.9. Use String#encode, etc. instead.
- There is ABI breakage [ruby-core:48984]. We think that normal users can/should just reinstall extension libraries. You should be aware: DO NOT COPY .so OR .bundle FILES FROM 1.9.
- #lines, #chars, #codepoints, #bytes now returns an Array instead of an Enumerator [#6670]. This change allows you to avoid the common idiom "lines.to_a". Use #each_line, etc. to get an Enumerator.
- Object#inspect does always return a string like #ClassName:0x... instead of delegating to #to_s. [#2152]

From [ruby-lang.org](http://www.ruby-lang.org/en/news/2013/02/24/ruby-2-0-0-p0-is-released#Incompatibility)

So it shouldn't be a big deal.

**Comment by nickserv** [comment]
Thanks for the info @kristenmills. Yeah, these issues shouldn't affect us, since they're fairly specific things and Rails is known to be okay with Ruby 2.0 anyway.

**Comment by nickserv** [comment]
We're still focusing primarily on Ruby 1.9.3 development because of Rubinius, but we will want to at least test with Ruby 2.0 to make transitioning to it easier in the future. Hopefully Travis will start supporting Ruby 2.0 soon.

**Comment by nickserv** [comment]
Never mind, I'm stupid. Travis uses RVM (or something like that), and it already supports Ruby 2. 

Because our tests are now passing with Ruby 2 (yay!), and due to Rails's known support of Ruby 2, I consider this issue done. However, we will still deploy using Ruby 1.9.3 (for now).
