### ISSUE TITLE
Removing Downvotes

### ISSUE THREAD

**Issue by kristenmills** [toroidal-code/codeflash#183]
So Kate Dorrene, and I were talking and we thought downvotes might be a bad idea. If we have downvotes, we are discouraging people who are learning. So maybe just having upvotes is a good idea. Another idea is having unreviewable code and that can be set by the user. 

I don't know. Discuss.

**Comment by toroidal-code** [comment]
What about only allowing downvotes if there is a comment explaining how the code could be improved.

**Comment by nickserv** [comment]
I think we should keep downvotes. Downvotes on Reddit and Stack Overflow are important for keeping content serious, appropriate, and non-trivial. I think that we will run into issues with users posting bad code if we remove downvotes.

Example:
Someone writes a really lame solution for a problem that's flawed and doesn't completely solve it. Users unfamiliar with the programming language upvote it. If we only implement upvotes, a large number of users could vote on a bad solutions merely because a lot of people have seen the problem. Let's say this bad solution gets 1,000 viewers. 300 of them upvote it, not realizing it's flawed. Meanwhile, another much better solution to this problem gets only 200 views, but it results in 150 upvotes. Obviously this problem is better, but it gets less credit just because less people see it.

Also, I kind of agree with @toroidal-code's comment here. As I often do, I'd have to agree with Stack Overflow for this one. Stack Overflow reminds users to comment on answers they downvote to explain why they didn't, but it doesn't require it. However, you lose reputation when downvoting! This can prevent spammy downvotes.

**Comment by kristenmills** [comment]
> I think we should keep downvotes. Downvotes on Reddit and Stack Overflow are important for keeping content serious, appropriate, and non-trivial. I think that we will run into issues with users posting bad code if we remove downvotes.

But the thing is we don't want to punish users for posting bad code. We want people to come here to learn languages. So basically what you are saying is if you are learning and you aren't very good you should be downvoted into oblivion.  It makes sense for Reddit and Stack Overflow.  It doesn't make sense for us. We have flagging. If something is so god awful that it should be removed from the site, a user can report it. I'd rather we encourage commenting on solutions and telling people what's flawed about it as opposed to just downvoting it. 

> Someone writes a really lame solution for a problem that's flawed and doesn't completely solve it. Users unfamiliar with the programming language upvote it. If we only implement upvotes, a large number of users could vote on a bad solutions merely because a lot of people have seen the problem. Let's say this bad solution gets 1,000 viewers. 300 of them upvote it, not realizing it's flawed. Meanwhile, another much better solution to this problem gets only 200 views, but it results in 150 upvotes. Obviously this problem is better, but it gets less credit just because less people see it.

Adding downvotes doesn't change that. And technically you can un upvote. Or at least that's what I was thinking you could eventually do. Also if the top voted solution does not ACTUALLY work, they probably just shouldn't receive an achievement. The highest voted working solution should. But regardless, I really want it to be focused on learning languages and your reasons for wanting downvotes really inhibits that. 

> What about only allowing downvotes if there is a comment explaining how the code could be improved.

I still think downvotes are discouraging so i'm against it. I really think it should be a thing where if a solution is great, give it a thumbs up. If it's not great, don't rate it or leave a comment saying what's wrong with it.

**Comment by toroidal-code** [comment]
I think removing downvotes would help, but I don't know how much. If something isn't that good, it would simply not be upvoted. I think we can safely remove them from solution without too much impact. On comments, I think downvotes should still exist. That way, we can safely hide comments the way youtube does once the community deems them to be neither constructive or helpful. IDK. this is a difficult topic, it requires more discussion.

**Comment by kristenmills** [comment]
> I think removing downvotes would help, but I don't know how much. If something isn't that good, it would simply not be upvoted. I think we can safely remove them from solution without too much impact.

Agreed

> On comments, I think downvotes should still exist. That way, we can safely hide comments the way youtube does once the community deems them to be neither constructive or helpful. 

I can live with that. 

> IDK. this is a difficult topic, it requires more discussion.

Yeah. This can be a saturday meeting thing since we'll all be there.

**Comment by StacyJCarlos** [comment]
I'm going to have to agree with Kristen nearly 100% on this issue. Posting bad code should never be a punishment because there are countless others who have posted solutions to the same problems so someone could easily look at other posts.

If someone wants to look at a good way to solve the problem they could easily look at the chosen  implementation. 

Upvotes for code be removed once the user has experience, but downvotes should only be allowed for comments the way Kate suggested in my opinion, because, as Kristen said, we don't want to discourage learners, but we do want people spanning bad comments or corrections.

Another thing that I think Nicolas is assuming is that the majority of users will be inexperienced and that all aspects of good coding can't transfer between languages, which may be true, but I seriously doubt that. I assume that the people who become members and actually upvote know something about the language before deciding. Unlike Reddit, this site isn't based heavily on personal likes and dislikes, but good coding practice.

One final note is that there isn't a final version of someones implementation, they could easily change it so having a downvote sit on their implementation unless until that user notices the changes which is bad. Although the same could be said if an implentation gets worse, but that would rarely happen I think.
