### ISSUE TITLE
What reasons should go in the reasons drop down for flagging?

### ISSUE THREAD

**Issue by kristenmills** [toroidal-code/codeflash#190]
Compile a list. READY GO

**Comment by nickserv** [comment]
Rogue.

**Comment by kristenmills** [comment]
Not constructive

**Comment by nickserv** [comment]
**Source Code:**
- **Plagiarised or duplicate code.** The poster copied code directly from another solution or another website/person (whether it's intentional or not, though there should be some leeway for more trivial solutions).
- **Malicious code.** The code is harmful, and could cause something along the lines of a fork bomb or a mass file deletion.
- **Does not attempt to solve problem.** The code does not even make an attempt to solve the given problem. Basically, the solution is off topic. Note that code that does not work should not necessarily be flagged as this, as it's most likely still an attempt at solving the problem. This flag also includes solutions that were posted for the wrong problem.
- **Intentionally obfuscated code.** The code is minified, a binary is given, or all whitespace is removed (or something like that). This does not include code that is poorly/not commented, and only involves users trying to make it impossible for other users to understand their solutions.
- **Obviously ported between languages automatically.** The code was quite obviously generated by some sort of cross compiler. For example, someone posts a solution in CoffeeScript, compiles it to JavaScript, and then posts another solution under JavaScript with the output. This encourages users to make thoughtful ports between languages, instead of trying to generate source code for similar languages merely to gain points.
- **Wrong language.** The code was submitted under the wrong language. Useful is someone posts a great solution but accidentally categorizes it wrong.
- **Not code.** The user did not actually post source code. They posted meaningless text, a description of how to solve the problem, pseudocode, or the actual solution to the problem, instead of code that solves the problem.

**Comments and Source Code:**
- **Spam.** The post has spammy content, such as pointless links to other sites.
- **Off topic.** The post has nothing to do with the current discussion and/or the discussion got too far off topic.
- **Content not in English.** The post is written in a (spoken) language other than English. Codeflash will start off as an English-only website (at least, I assume so).
- **Unconstructive content.** The post does not aid the discussion. Example: Pointless arguing over the specifics of a small portion of a solution.
- **Inappropriate content.** The post contains content that is sexually explicit, illegal, contains cursing, etc. (We might want to elaborate on whether all cursing is banned, or if we let it slide to an extent.)
- **Offensive content.** The post contains content that is racist, sexist, offensive, or just generally attacks one or more other users.

**Comment by nickserv** [comment]
To clarify, is this only for solutions/code and comments so far?

**Comment by kristenmills** [comment]
yeah

**Comment by kristenmills** [comment]
those are good.

**Comment by nickserv** [comment]
Should we put the flag explanations from my comment above into either the flagging UI or some sort of help page? I think it would be nice if we could do both. I mean, we'd have to modify the text a little to be more suitable to users first.

**Comment by StacyJCarlos** [comment]
It should go to on the rules page and their maybe should be a link to it on the drop down menu.

**Comment by nickserv** [comment]
Agreed, or we could have little popovers, but that probably wouldn't work well with a drop down menu.

**Comment by nickserv** [comment]
Since @kristenmills's original question was answered and this is a planning issue, I will close it. I'll make another issue to remind myself to put my flag descriptions somewhere.
