### ISSUE TITLE
How will achievements be assigned to a user?

### ISSUE THREAD

**Issue by smy2748** [toroidal-code/codeflash#2]
We spoke of including achievements for various things (such as being able to do a problem within an esoteric language.)  How will these be assigned?  

I believe one idea we've covered is having a moderator nominate a solution for an achievement and have people vote on it.

**Comment by nickserv** [comment]
How about a central list of achievements, with each achievement keeping track of all the users that completed it?

And if you're talking about how it would work administratively, I think there should be a set list of achivements that mods can edit. I don't think that we should just give achievements if we like someone's work, that's what upvotes are for. I'm thinking about achievements being more of fun bonus goals, like "reimplement all of Codeflash in Common Lisp".

**Comment by kristenmills** [comment]
It wouldn't be giving achievements if we like peoples work. I think achievement solutions should be separate from regular solutions. Then we need a way to indicate whether that solution is applicable to the achievement that it was associated with. And voting is the best way to do that.

**Comment by nickserv** [comment]
I like the idea of separating achievement solutions from regular solutions. However, I think we might not even need a voting system for most/all achievements, since we could use an automated tracking system instead.

Example achievements:
- get a best solution
- solve one problem for every language family
- get a best solution for every language family (they can be across multiple problems)
- be one of the first users on the site
- reach a certain level/number of points
- write the shortest good (but not necessarily winning) solution for a problem
- reimplement the entire site using only Common Lisp

**Comment by kristenmills** [comment]
But the thing is for certain  ones like "reimplement the entire site using only Common Lisp", an automated system wouldn't be good. How are we going to prove that it actually works using an automated system?

**Comment by smy2748** [comment]
We could break down achievements into multiple categories as we go on.  Have certain achievements be "automatic," some assigned by moderators/admins, and some based on a nomination and voting system (constraints of this system to be discussed later.)

**Comment by nickserv** [comment]
I like that idea, but I still feel that achievements would work better if they were all automated. As for "implement x in y language" kinds of achievements, we might be able to set up some sort of minimal testing system for solutions, and solutions could have hidden (or visible) tests that would have to pass for valid solutions or for achievements.

Also, do you have any ideas for non-automated achievements? I'm curious what kinds of user/mod-chosen achievements you're thinking of, since I don't want achievements to turn into "my solution was already popular and I already got a lot of points for it, but it happened to be in Perl so I also got an achievement".

EDIT: Also, if we do have votable achievements, how will we handle keeping achievement votes separate from normal solution votes? Do users add achievement votes to solutions? Or do people add a solution nominee to an achievement?

**Comment by smy2748** [comment]
Moderator chosen achievements would be given based on a moderator or administrator noticing that a user has contributed significantly to the site in some manner or another.  These would only really be given out on special occasions and are going to be unique for the most part.

User voted achievements I was thinking would act as a sort of community awards.  So this would allow for a "solution of the month" sort of thing where the community could choose which solution they believed was especially clever or which user they felt was especially helpful in reviewing code.  

I was thinking that we could limit nominations for these awards to either one nomination per user or have something based off of their total score.  Users cannot nominate themselves.  Nominations have to be checked by a moderator for legitimacy (although we may be able to automate this for some of the achievements.)  Essentially, the idea would be to encourage high-quality over high-quantity.  

Most of these ideas are pretty far down the road in terms of actually adding them, but it's a good idea to think about hem so we can make it easy to add them in later.

**Comment by StacyJCarlos** [comment]
I going to agree with Yingling. The idea of moderator and user achievements being separate will ensure that people that contribute to the site and communicate with other members are rewarded. 

As far as nominations go, I'm not sure because of how people nominate someone. It might be because their solution is the best or because they just prefer one person over the other which will be very hard to control.

**Comment by kristenmills** [comment]
I agree with yingling and stacy

**Comment by nickserv** [comment]
I like this idea too. Did you guys want to drop automated achievements?

**Comment by kristenmills** [comment]
Well I mean i do like the best solution achievements and those can pretty much be automated. So i wouldn't say get rid of them all together. But when would those achievements be awarded?

**Comment by StacyJCarlos** [comment]
As far as achievements go, I think we have two ways of doing it. One, we could make then static so that anyone can get any achievement for their implementation. A second option could be a badge system. By this I mean we create an achievement with some sort of badge and if people submit the achievement before the time is up they get it.

Of course the benefits with the first are that people feel equal no matter when they enter and can jump right in. However, the latter promotes people to use the site on a daily basis to get the constantly updating achievements.

**Comment by nickserv** [comment]
:+1:

**Comment by nickserv** [comment]
Do we have some sort of consensus on what we want to do for achievements now?

**Comment by smy2748** [comment]
Literally Hitler.

**Comment by nickserv** [comment]
Is this issue ready to be closed?

**Comment by smy2748** [comment]
More or less.  I'd say link to the related issue and close it.

**Comment by kristenmills** [comment]
Updated the wiki. Closing the issue
