### ISSUE TITLE
Switch server to Puma

### ISSUE THREAD

**Issue by nickserv** [toroidal-code/codeflash#27]

**Comment by toroidal-code** [comment]
Applied by a534c40b3853a4d95f4ec537ce9f24b55ceb138f

**Comment by nickserv** [comment]
By the way, you can add "fix #27" somewhere in your commit message and GitHub will automatically add a link in the issue to your commit and close it for you when it reaches the master branch.

**Comment by kristenmills** [comment]
or fixes or fixed or closes or close or closed.

**Comment by nickserv** [comment]
1. "or" should be capitalized.
2. That is still a sentence fragment.

**Comment by kristenmills** [comment]
![](http://i.minus.com/i1vEax18zB1lG.gif)

**Comment by kristenmills** [comment]
What is the `-s` in the config.ru? That flag causes `rails server` to error out.

**Comment by toroidal-code** [comment]
you should be using `rackup`. since we're running ruby on rails on rack, the `rails s` command shouldn't be used: http://guides.rubyonrails.org/rails_on_rack.html
the `#\ -s puma` makes the default `rackup` command execute as `rackup -s puma`. if you would prefer to use the `rails` command, remove that line from the config.ru and execute `rails s puma`

**Comment by nickserv** [comment]
Aren't you supposed to be using "rails server" to start Rails apps instead
of rackup? I could be wrong, but I thought rackup didn't work for Rails.

**Comment by toroidal-code** [comment]
The Rails::Server inherits from Rack::Server and calls the Rack::Server#start method

**Comment by nickserv** [comment]
I just found out that `bundle exec rackup` works fine for me on the dev branch. The port changes to 9292, though.

If you want to keep using rackup, you/we should update the docs.
