### ISSUE TITLE
Rake task for toggling admin status on users

### ISSUE THREAD

**Issue by nickserv** [toroidal-code/codeflash#72]
It would simply run this command on the database:
`UPDATE users SET admin = 't' WHERE username = 'god';`

Documentation on this should be in the getting started guide.

**Comment by smy2748** [comment]
Why does this need to be a rake task?  Couldn't you just run the command?  Otherwise we'll need to create a default admin user for all of us to use and blah blah blah security issues.  Also, that doesn't toggle admin status, it enables admin status.  Also :-1: 

![](http://www.reactiongifs.com/wp-content/uploads/2013/01/relieved.gif)

**Comment by nickserv** [comment]
I'll add this to the wiki for now. In the future I'll make some automated thing if people still want it.
