### ISSUE TITLE
Displaying code.

### ISSUE THREAD

**Issue by kristenmills** [toroidal-code/codeflash#74]
how do we want to display code?  We can do ace editor read only mode. That would be pretty chill bro chill.

**Comment by toroidal-code** [comment]
I really like the look of http://craig.is/making/rainbows

**Comment by toroidal-code** [comment]
That way we don't have to embed an editor into every solution element on the solutions page.

**Comment by nickserv** [comment]
I like both Ace and Rainbows, and I like the idea of not loading Ace editors everywhere, but I think we should make sure we have the same theme everywhere for consistency.

**Comment by nickserv** [comment]
Also, I think BootStrap has code highlighting support.

**Comment by kristenmills** [comment]
[highlight.js](https://github.com/isagalaev/highlight.js) is a possibility. It has support for more languages than rainbows and it has autodetection...if we want that.

**Comment by nickserv** [comment]
Which one does Bootstrap have built in integration for?

**Comment by kristenmills** [comment]
are you sure bootstrap has built in integration?

**Comment by kristenmills** [comment]
I'm pretty sure it doesn't.

**Comment by toroidal-code** [comment]
yeah, I don't think it does.

**Comment by nickserv** [comment]
Hm, it seems like it doesn't now. o_o

**Comment by toroidal-code** [comment]
highlight.js looks really nice

**Comment by nickserv** [comment]
It does look pretty cool, but that's client side and would probably require JavaScript.

We can use [pygments.rb](https://github.com/tmm1/pygments.rb), which is what GitHub uses. It's a Ruby wrapper for Pygments, a server-side highlighter for Python.

EDIT: Changed the wrapper gem I'm talking about to pygments.rb, since Albino is deprecated.

**Comment by toroidal-code** [comment]
albino has been deprecated

**Comment by kristenmills** [comment]
yeah

**Comment by nickserv** [comment]
Please read my comment again, I edited it.

**Comment by toroidal-code** [comment]
also, pygments requires a python process. and a 2.x one at that. I don't think it's a good idea to be running more processes server-side

**Comment by toroidal-code** [comment]
Not only that, but it spawns a python process for every instance of pygments. That's a little much if we're running on a single server

**Comment by toroidal-code** [comment]
Also, I like the idea of giving users the ability to choose the theme for displaying code on the site if they're logged in. with highlight.js, that's not too difficult.

**Comment by kristenmills** [comment]
yeah highlight.js seems like a way better option.

**Comment by nickserv** [comment]
Ewww I didn't realize that Kate. Let's do highlight.js.

**Comment by kristenmills** [comment]
I'm closing this and assuming this decided.

**Comment by kristenmills** [comment]
highlights syntax highlighting is kind of terrible. pygments might be the way to go.

**Comment by toroidal-code** [comment]
what makes you think that the highlighting is terrible?

**Comment by nickserv** [comment]
I think we should try spawning Ace editors in read only mode. Since we already need to load the Ace editor for edit pages, it will already be cached, so it shouldn't be a big issue to also use it for displaying code as long as it doesn't hog resources on the client side too much. Also, we won't have to worry about using the same theme across different client side software, since we can simply use the edit theme as our display theme as well.

**Comment by kristenmills** [comment]
i agree.
